.TH SHUTDOWN 8 "12 September 2014" "Runit for LFS"
.SH NAME
.B shutdown
- bring down the system
.SH SYNOPSIS
.B shutdown \fR[\fB-rhP\fR] [\fB-fF\fR] [\fB-ck\fR] [\fBnow\fR | \fB+\fImins\fR] [\fImessage\fR]
.SH DESCRIPTION
.B shutdown
brings the system down in a secure way. All logged-in users are notified that the system is going down, and login(1) is blocked.
.PP
By default,
.B shutdown
puts the system into single user mode. Rebooting and halting the system can be done using the following options:
.TP
.B -c
Cancel an ongoing shutdown.
.TP
.B -f
Enable fast booting; skip fsck(8) on next boot.
.TP
.B -F
Force run of fsck(8) on next boot.
.TP
.B -h
Halt the system.
.TP
.B -k
Don't really shutdown; only send the warning messages to everybody.
.TP
.B -P
Poweroff the system.
.TP
.B -r
Reboot the system.
.TP
.B now
Shutdown without further waiting.
.TP
.B +\fImins\fP
Wait \fImins\fP minutes before shutting down.
.TP
\fImessage\fP
Message displayed to all users, defaults to "system is going down".
.SH UNSUPPORTED OPTIONS
.PP
This version of
.B shutdown
is based on runit(8) and the following features are not supported:
.TP
.B -t \fP\fIsecs\fP
wait \fIsecs\fP seconds between SIGKILL and SIGTERM on shutdown is silently ignored.
.TP
.B -a
Use /etc/shutdown.allow.
.TP
.B -H
Drop into boot monitor.
.TP
.B -n
Don't call init(8).
.TP
\fIhh:mm\fP
Absolute time specification is not implemented.
.SH EXAMPLES
.TP
Halt and poweroff without delay...
# shutdown -h now
.TP
Reboot in five minutes...
# shutdown -r +5
.PP
.SH SEE ALSO
fsck(8), init(8), runit(8), runsvchdir(8), halt(8), poweroff(8), reboot(8)
.SH AUTHOR
Christian Neukirchen,
chneukirchen@gmail.com
.br
This man page was edited and reformatted for runit-for-lfs.
