#!/bin/sh
exec 2>&1
[ -r /etc/sysconfig/mouse ] && . /etc/sysconfig/mouse
if [ -z "$MDEVICE" ] || [ -z "$PROTOCOL" ]; then
   echo "Please create an /etc/sysconfig/mouse file"
   echo "containing MDEVICE and PROTOCOL values."
   exit 1
fi
exec gpm -D -m $MDEVICE -t $PROTOCOL &> /dev/null